// このファイルは tools/gen_art.py で自動生成されています。直接編集しないでください。
#pragma once

// 支援ページ ko-fi.com/daipoyo の QR（バージョン1、余白 4マス込み）
#define QR_SUPPORT_URL "ko-fi.com/daipoyo"
#define QR_SUPPORT_SIZE 29

static const char *const QR_SUPPORT[QR_SUPPORT_SIZE] = {
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "WWWWKKKKKKKWWKKKWWKKKKKKKWWWW",
  "WWWWKWWWWWKWKWWKKWKWWWWWKWWWW",
  "WWWWKWKKKWKWWWWKWWKWKKKWKWWWW",
  "WWWWKWKKKWKWKKKKWWKWKKKWKWWWW",
  "WWWWKWKKKWKWWWKWWWKWKKKWKWWWW",
  "WWWWKWWWWWKWKWKKKWKWWWWWKWWWW",
  "WWWWKKKKKKKWKWKWKWKKKKKKKWWWW",
  "WWWWWWWWWWWWWKWWKWWWWWWWWWWWW",
  "WWWWKKKKKWKKKKWWKKWKWKWKWWWWW",
  "WWWWKKKKWWWKWWKKWKKKKKWWKWWWW",
  "WWWWKWKKKKKKWKWKKKKWWKWKWWWWW",
  "WWWWKKKWWKWWKKWKKKWWKWKKKWWWW",
  "WWWWWWKKKWKKWKWWWWKKWWWWKWWWW",
  "WWWWWWWWWWWWKKKWWKKKKKWWKWWWW",
  "WWWWKKKKKKKWKWKKKKWWWKKKWWWWW",
  "WWWWKWWWWWKWWWWKKWWKKKKKWWWWW",
  "WWWWKWKKKWKWKWKWKWKWKWWWWWWWW",
  "WWWWKWKKKWKWKKKWWKKKKKKKWWWWW",
  "WWWWKWKKKWKWKWKKKKKKWWWWWWWWW",
  "WWWWKWWWWWKWKWWWKKWWWKKWWWWWW",
  "WWWWKKKKKKKWKKWKKWKKKWWKWWWWW",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
  "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
};
